Repository AvalonXR/Avalon, pull requests merged in 2023-12, with the labels that each got.

#11 ci: Add detekt plugin to gradle config
  build.gradle.kts
  config/detekt.yml
  gradle/libs.versions.toml
  src/main/kotlin/xyz/avalonxr/config/AppSettings.kt
  src/main/kotlin/xyz/avalonxr/data/CommandResult.kt
  src/main/kotlin/xyz/avalonxr/data/OptionStore.kt
  src/main/kotlin/xyz/avalonxr/data/error/AvalonError.kt
  src/main/kotlin/xyz/avalonxr/data/error/CommonError.kt
  src/main/kotlin/xyz/avalonxr/dsl/discord/CommandDsl.kt
  src/main/kotlin/xyz/avalonxr/enums/ExitCode.kt
  src/main/kotlin/xyz/avalonxr/enums/ExitHandlerStrategy.kt
  src/main/kotlin/xyz/avalonxr/handler/Handler.kt
  src/main/kotlin/xyz/avalonxr/handler/exit/ApplicationExitHandler.kt
  src/main/kotlin/xyz/avalonxr/handler/exit/DebugOnExit.kt
  src/main/kotlin/xyz/avalonxr/handler/exit/ExceptionOnError.kt
  src/main/kotlin/xyz/avalonxr/handler/exit/LogOnExit.kt
  src/main/kotlin/xyz/avalonxr/message/ExitMessage.kt
  src/main/kotlin/xyz/avalonxr/message/Message.kt
  src/main/kotlin/xyz/avalonxr/models/Types.kt
  src/main/kotlin/xyz/avalonxr/models/discord/Command.kt
  src/main/kotlin/xyz/avalonxr/models/discord/EventListener.kt
  src/main/kotlin/xyz/avalonxr/service/LifecycleService.kt
  src/main/kotlin/xyz/avalonxr/validation/service/MultiValidationService.kt
  src/main/kotlin/xyz/avalonxr/validation/service/SingleValidationService.kt
  src/main/kotlin/xyz/avalonxr/validation/validator/MultiValidator.kt
  src/main/kotlin/xyz/avalonxr/validation/validator/SingleValidator.kt
  src/test/kotlin/xyz/avalonxr/dsl/discord/CommandDslSpec.kt
  src/test/kotlin/xyz/avalonxr/dsl/discord/EmbedDslSpec.kt
  src/test/kotlin/xyz/avalonxr/enums/ExitHandlerStrategySpec.kt
  src/test/kotlin/xyz/avalonxr/validation/service/MockValidationService.kt
  src/test/kotlin/xyz/avalonxr/validation/service/MockValidationServiceSpec.kt
  src/test/kotlin/xyz/avalonxr/validation/validator/MockValidator.kt
  src/test/kotlin/xyz/avalonxr/validation/validator/MockValidatorSpec.kt
Labels: enhancement

#20 ci: Add GitHub Actions PR script.
  .github/build.yml
  config/detekt.yml
Labels: enhancement

#28 feat: Add basic command service
  config/detekt.yml
  src/main/kotlin/xyz/avalonxr/annotations/AvalonCommand.kt
  src/main/kotlin/xyz/avalonxr/data/CommandResult.kt
  src/main/kotlin/xyz/avalonxr/data/Payload.kt
  src/main/kotlin/xyz/avalonxr/data/error/CommandError.kt
  src/main/kotlin/xyz/avalonxr/service/command/CommandService.kt
  src/test/kotlin/xyz/avalonxr/fixtures/discord/ApplicationCommandInteractionOptionFixture.kt
  src/test/kotlin/xyz/avalonxr/fixtures/discord/ApplicationCommandInteractionOptionValueFixture.kt
  src/test/kotlin/xyz/avalonxr/fixtures/discord/ChatInputInteractionEventFixture.kt
  src/test/kotlin/xyz/avalonxr/fixtures/discord/InteractionFixture.kt
  src/test/kotlin/xyz/avalonxr/fixtures/discord/UserFixture.kt
  src/test/kotlin/xyz/avalonxr/models/discord/TestCommand.kt
  src/test/kotlin/xyz/avalonxr/service/command/CommandServiceSpec.kt
Labels: enhancement

#31 feat: Implement command binding service
  src/main/kotlin/xyz/avalonxr/binding/discord/command/CommandBinder.kt
  src/main/kotlin/xyz/avalonxr/binding/discord/command/GlobalCommandBinder.kt
  src/main/kotlin/xyz/avalonxr/binding/discord/command/GuildCommandBinder.kt
  src/main/kotlin/xyz/avalonxr/data/command/CommandBinding.kt
  src/main/kotlin/xyz/avalonxr/enums/CommandScope.kt
  src/main/kotlin/xyz/avalonxr/events/SpringApplicationStartedListener.kt
  src/main/kotlin/xyz/avalonxr/provider/DiscordClientProvider.kt
  src/main/kotlin/xyz/avalonxr/service/command/CommandService.kt
  src/main/kotlin/xyz/avalonxr/service/command/CommandValidationService.kt
  src/main/kotlin/xyz/avalonxr/service/discord/DiscordBindingService.kt
  src/main/resources/application.yml
Labels: enhancement

#36 feat: Add new getOrDefault function to OptionStore
  src/main/kotlin/xyz/avalonxr/command/PingCommand.kt
  src/main/kotlin/xyz/avalonxr/data/OptionStore.kt
Labels: enhancement

#37 feat: Add default command handler
  src/main/kotlin/xyz/avalonxr/data/error/CommandError.kt
  src/main/kotlin/xyz/avalonxr/handler/command/AvalonDefaultCommandHandler.kt
  src/main/kotlin/xyz/avalonxr/handler/command/DefaultCommandHandler.kt
  src/main/kotlin/xyz/avalonxr/service/command/CommandService.kt
  src/main/kotlin/xyz/avalonxr/utils/MessageUtils.kt
  src/test/kotlin/xyz/avalonxr/service/command/CommandServiceSpec.kt
Labels: enhancement

#38 feat: Add support for JPA entities and repositories
  build.gradle.kts
  gradle/libs.versions.toml
  src/main/kotlin/xyz/avalonxr/data/entity/WelcomeMessage.kt
  src/main/kotlin/xyz/avalonxr/repository/WelcomeMessageRepository.kt
  src/main/resources/application.yml
  src/main/resources/sql/test/welcome_message_test.sql
  src/test/kotlin/xyz/avalonxr/repository/WelcomeMessageRepositorySpec.kt
  src/test/resources/application.yml
Labels: enhancement

#39 fix: Postgres configuration issues
  gradle/libs.versions.toml
  src/main/resources/application.yml
Labels: bug

#41 fix: Add better support for subcommands
  src/main/kotlin/xyz/avalonxr/data/OptionStore.kt
  src/main/kotlin/xyz/avalonxr/dsl/discord/CommandDsl.kt
  src/main/kotlin/xyz/avalonxr/service/command/CommandService.kt
Labels: bug

#43 feat: Add channel helper function to OptionStore
  src/main/kotlin/xyz/avalonxr/data/OptionStore.kt
Labels: enhancement

#44 chore: Add default command handler for after a command has executed
  src/main/kotlin/xyz/avalonxr/handler/command/AvalonDefaultCommandHandler.kt
  src/main/kotlin/xyz/avalonxr/handler/command/DefaultCommandHandler.kt
  src/main/kotlin/xyz/avalonxr/service/command/CommandService.kt
  src/main/kotlin/xyz/avalonxr/utils/MessageUtils.kt
  src/test/kotlin/xyz/avalonxr/fixtures/discord/ChatInputInteractionEventFixture.kt
  src/test/kotlin/xyz/avalonxr/fixtures/discord/MessageFixture.kt
  src/test/kotlin/xyz/avalonxr/service/command/CommandServiceSpec.kt
Labels: chore

#45 fix: Fix exceptions in default handler
  src/main/kotlin/xyz/avalonxr/handler/command/AvalonDefaultCommandHandler.kt
  src/main/kotlin/xyz/avalonxr/utils/MessageUtils.kt
Labels: bug

#46 chore: Add more Discord utility classes
  src/main/kotlin/xyz/avalonxr/utils/ChannelUtils.kt
  src/main/kotlin/xyz/avalonxr/utils/GuildUtils.kt
Labels: chore

#47 feat: Add ValidatedOptional for 3-way state checks
  src/main/kotlin/xyz/avalonxr/data/OptionStore.kt
  src/main/kotlin/xyz/avalonxr/data/ValidatedOptional.kt
Labels: feature

#49 feat: Add string templating service
  src/main/kotlin/xyz/avalonxr/data/format/ChannelMentionFormatter.kt
  src/main/kotlin/xyz/avalonxr/data/format/GuildNameFormatter.kt
  src/main/kotlin/xyz/avalonxr/data/format/TimestampFormatter.kt
  src/main/kotlin/xyz/avalonxr/data/format/UsernameFormatter.kt
  src/main/kotlin/xyz/avalonxr/models/discord/DiscordStringFormatter.kt
  src/main/kotlin/xyz/avalonxr/service/FormatService.kt
Labels: feature

#42 feat: Add welcome message configuration command and subcommands
  src/main/kotlin/xyz/avalonxr/command/WelcomeCommand.kt
  src/main/kotlin/xyz/avalonxr/data/error/CommandError.kt
  src/main/kotlin/xyz/avalonxr/service/FormatService.kt
Labels: feature

#50 feat: Add welcome clear subcommand.
  src/main/kotlin/xyz/avalonxr/command/WelcomeCommand.kt
  src/main/kotlin/xyz/avalonxr/repository/WelcomeMessageRepository.kt
Labels: feature

#51 feat: Update CommandResult with extra functions and state classes
  src/main/kotlin/xyz/avalonxr/command/PingCommand.kt
  src/main/kotlin/xyz/avalonxr/command/WelcomeCommand.kt
  src/main/kotlin/xyz/avalonxr/data/CommandResult.kt
  src/main/kotlin/xyz/avalonxr/data/Payload.kt
  src/main/kotlin/xyz/avalonxr/handler/command/AvalonDefaultCommandHandler.kt
  src/test/kotlin/xyz/avalonxr/service/command/CommandServiceSpec.kt
Labels: feature
